# Generated by Django 2.1 on 2018-08-29 11:59

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.PositiveSmallIntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期七')], default=0)),
                ('time_length', models.PositiveIntegerField(default=120)),
                ('total_sec', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('is_cancel', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher_id',
            field=models.ForeignKey(on_delete=models.SET(courses.models.get_teacher), related_name='teacher', to='courses.Teacher'),
        ),
    ]
