# Generated by Django 2.1 on 2018-08-29 11:59

import datas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('customers', '0002_auto_20180829_1159'),
        ('datas', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrecord',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_record', to='users.SellerInfo'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='cc',
            field=models.ForeignKey(null=True, on_delete=models.SET(datas.models.get_user), related_name='review_refund', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='course',
            field=models.ForeignKey(on_delete=models.SET(datas.models.get_course), related_name='refund_record', to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='customer',
            field=models.ForeignKey(on_delete=models.SET(datas.models.get_customer), related_name='refund_record', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='otherresource',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='operationlogs',
            name='operator',
            field=models.ForeignKey(on_delete=models.SET(datas.models.get_user), related_name='user_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ccrecord',
            name='cc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ccrecord',
            name='course',
            field=models.ForeignKey(null=True, on_delete=models.SET(datas.models.get_course), related_name='signup_record', to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='ccrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_record', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='auditionrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audition_record', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='auditionrecord',
            name='section',
            field=models.ForeignKey(null=True, on_delete=models.SET(datas.models.get_section), related_name='audition_record', to='courses.Section'),
        ),
    ]
